### ISSUE TITLE
Regarding updataing the plumed version (gromacs_plumed)

### ISSUE THREAD

**Issue by srp106** [intbio/MolModEdu#1]
Hi,

If possible, could you please upgrade the plumed version to 2.5.2. (conda package)
so that we all can use the SAX modules implemented in plumed.  https://www.plumed.org/doc-v2.5/user-doc/html/isdb-2.html

Thank you

**Comment by molsim** [comment]
Hi, pls, submit the ticket into the relevant repo https://github.com/intbio/plumed-conda
we'll try to do an update
